name: sensor.postnl
description: Package feed reader for PostNL json file
type: component
keywords:
  - sensor
  - PostNL
author:
  name: Eelco Bode 
license: MIT
files:
  - custom_components/feedparser/sensor.py
  - custom_components/feedparser/manifest.json
  - custom_components/feedparser/__init__.py
